### ISSUE TITLE
Dev install fails without Jupyter lab

### ISSUE THREAD

**Issue by jdemeyer** [ipython/ipywidgets#1012]
The relation between ipywidgets and jupyterlab is not so clear to me.

Is there a compelling reason why `dev-install.sh` requires Jupyterlab to be installed? I could easily change that script to skip the installation of `jupyterlab_widgets` if Jupyterlab is not installed. Would that be a good idea?

**Comment by SylvainCorlay** [comment]
I think that it is the right thing to do to have the dev installation to require jupyterlab since it is the future main target environment for widgets.


Regarding the dependency order

A `ipywidgets` is the kernel-side package
B1 `widgetsnbextension` is the notebook-server-side notebook extension package (which could be in a different environement than the kernel)
B2 `jupyterlab_widgets` is the notebook-server-side lab extension package (which could be in a different environement than the kernel)


The logical dependency direction is that ipywidgets should be installable without widgetsnbextension of jupyterlab_widgets, and reversely.

However, we kept the feature that ipywidgets should be usable as a standalone package for someone who installs everything (kernel and client) in the same environment.

**Comment by jdemeyer** [comment]
It's not a big issue, but I did find it surprising/confusing that ipywidgets itself does not require Jupyterlab, but the dev install does require Jupyterlab. Why not allow the option of doing the dev install without Jupyterlab for people who don't care about Jupyterlab?

**Comment by SylvainCorlay** [comment]
> Why not allow the option of doing the dev install without Jupyterlab for people who don't care about Jupyterlab?

For now, we don't depend on jupyterlab. This is only the dev-install script. To be honest, I don't use this script personally.

**Comment by jasongrout** [comment]
I don't use the dev install script either. I did add the JLab stuff there to help someone else who was doing widgets in JLab. We could put the JLab stuff behind a switch if you want.

**Comment by hainm** [comment]
if developers do not use it personally, why bothering to keep it to avoid confusion? :D

**Comment by SylvainCorlay** [comment]
Some occasional contributors requested it :)

**Comment by hainm** [comment]
ha, fair enough. I just wish all the Jupyter-related projects (Python+JS) have the same way to install packages for contributors.

**Comment by jdemeyer** [comment]
> We could put the JLab stuff behind a switch if you want.

See #1023.

**Comment by jasongrout** [comment]
Fixed in #1023.
