### ISSUE TITLE
Inconsistencies in docs and cookiecutter project

### ISSUE THREAD

**Issue by martinal** [ipython/ipywidgets#1052]
I've found a few inconsistencies in the docs or in the docs vs the cookiecutter widget project, probably caused by API changes at some point if I were to guess. I may be wrong, but my impression is that these are doing the same:
```
this.listenTo(...)
this.model.on(...)
```
and
```
this.save_changes()
this.touch()
```
The cookiecutter project uses `this.model.on`, while `listenTo` and `save_changes` are mentioned at:
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Low%20Level.html

`touch` is mentioned in the docs here without explaining its signature:
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html

If these are _not_ the same, the documentation is lacking as to what the difference is.

Also, the cookie cutter project uses `DOMWidgetModel` while the docs only mention `WidgetModel`, also at
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Low%20Level.html

**Comment by martinal** [comment]
Nevermind. Although I still think the documentation for ipywidgets is a bit thin, these are mostly from the Backbone.js API which is well documented.

**Comment by jasongrout** [comment]
It is definitely thin - thanks for bringing these up. Here is some info not in backbone:

`save_changes` just saves changes without providing a callback for output. `touch` does provide a callback for output, so that output produced as a result of the change can be seen by the user. Typically, a view will use `.touch()`. A model will use `save_changes`.

As for the widget models, if your model is representing an element in the DOM, it should probably use DOMWidgetModel. Some models do not represent elements on the page, and should use the more abstract WidgetModel (e.g., most of the models in pythreejs, which represent elements in the webgl scene graph, use WidgetModel).
