### ISSUE TITLE
JavaScript widget toolkit without jquery

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#140]
The IPython widgets framework allows for other backbone view types than the usual JQuery-based, and neither `widget.js` nor `manager.js` really depends on JQuery.

However, we still use bootstrap and JQuery for the core basic IPython widgets like button / slider / date picker, dropdown.

I was wondering what is the best JavaScript widget framework that we could use as a replacement, and that would play well with phosphor. I am not sure if it is in the scope of phosphor to reimplement those. Apparently, it is possible to use bootstrap's css without the JQuery extension. There are replacements to this extension such as https://github.com/tagawa/bootstrap-without-jquery

What do you guys think about it?

**Comment by SylvainCorlay** [comment]
@sccolbert @jdfreder this discussion could probably apply to other pieces of the front-end.

**Comment by sccolbert** [comment]
I'm busy refactoring Phosphor so that it can provide that type of leaf content. i.e. buttons, sliders, etc.. are now on the radar.

**Comment by SylvainCorlay** [comment]
As part of phosphor, or would you prefer using something like bootstrap?

**Comment by sccolbert** [comment]
As part of phosphor. But as usual, nothing would prevent you from using bootstrap with a phosphor widget if you wanted to.

**Comment by SylvainCorlay** [comment]
I would probably prefer using only *one* solution, and therefore use phosphor's basic widgets (however it is not here yet). 
Besides the widgets repo should probably work with both the new and the old front-end for some time, and depending on phosphor would also help for other things like the signaling...

**Comment by ellisonbg** [comment]
I think we should aim to have the interactive widgets be exactly the same
as we use elsewhere in our frontend UI. IOW, we shouldn't have two
different ButtonView (one for interactive widgets and another for our UI).
The two may and will be plugged into different models underneath, but that
is a separate issue.

I am +1 on not using jquery, although I think we are still using some of
the things from jquery.ui.

Bootstrap is still a pretty nice way of handling common UI elements. We
could roll our own, but would end up reinventing bootstrap in the process.

One option is to offer phosphor views that are simply wrappers around
bootstrap styled things.

I also think we should think carefully about scope limiting phosphor. I am
hesitant for it to start including all possible views needed to build
complex UIs. I think the messaging should be more around phosphor being the
foundation for building such things. That does raise the question about
what to do about the tab/panel layout stuff though.

Some of this does depend on how Chris's refactoring turns out.



On Mon, Aug 10, 2015 at 10:52 AM, Sylvain Corlay <notifications@github.com>
wrote:

> I would probably prefer using only *one* solution, and therefore use
> phosphor's basic widgets (however it is not here yet).
> Besides the widgets repo should probably work with both the new and the
> old front-end for some time, and depending on phosphor would also help for
> other things like the signaling...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/140#issuecomment-129548363>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by sccolbert** [comment]
As an fyi - I'm happy with the way the refactoring is turning out.

**Comment by jdfreder** [comment]
:+1: to some incarnation of jquery-free backbone widgets.  Marking as 5.0 because this definitely will be backwards incompatible.  :-1: to the idea of dropping bootstrap for 5.0 and/or trying to ship our own jquery-less bootstrap, I don't think it's worth the effort.  Maybe a later major release though...

**Comment by jasongrout** [comment]
The current master now has rewritten widgets that don't use jquery, *except* for the slider. I've opened #630 for that.
