### ISSUE TITLE
Setting IntRangeSlider readout to pick elements from an array-like object.

### ISSUE THREAD

**Issue by jgoad** [ipython/ipywidgets#172]
I've seen a few widget applications using the IntRangeSlider as a date selector, for example. It would be cool if the readout display values could be set dynamically.

**Comment by jgoad** [comment]
something like...

```
if self.value[0] == self.value[1]:
        if self.value[0] >= self.min and self.value[0]-1 >= self.min:
            self.value = (self.value[0]-1,self.value[1])
            
        else:
            self.value = (self.value[0],self.value[1]+1)
```

**Comment by jdfreder** [comment]
I'm not 100% clear on what you're asking here.  Are you asking to be able to hook range sliders up to other widgets?  Or are you asking to use the range to slice and array?

**Comment by jgoad** [comment]
the IntRangeSlider has a readout, right? It would be cool if you could set the readout to something else, like the elements of the array. A datetime widget would be really good.

**Comment by jdfreder** [comment]
Oh, I see.  Because the readout is editable, you'd haven't to provide conversion both ways, from numeric value to desired type, and from desired type back to numeric value.  You would have to do this in Javascript because the readout does not roundtrip to the backend; It's synced with the handles directly in the frontend.

This can be done in Javascript now by subclassing IntSliderView and overriding `update` and `handleTextChange`.  Unfortunately, you'd have to reimplement some of the other supporting logic too.  I can make this easier by separating the logic out, so the two Javascript functions you have to override are simple.
