### ISSUE TITLE
Browserify can only be used with string literals in the source code.

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#241]
A problem then is that the requirejs shim changing the arguments of `require` or `amdefine` prevent browserify to do its job correctly.

**Comment by jdfreder** [comment]
That's right, it's a limitation of browserify because browserify uses static analysis to build its dependency graph.  Is there a particular file that isn't working?  It may need to be defined in [the kludge](https://github.com/ipython/ipywidgets/blob/master/ipywidgets/static/widgets/js/requirejs-shim.js#L5-L15) which is how I make it all work.

**Comment by jdfreder** [comment]
Please reopen if you find a file is missing in aforementioned kludge.

**Comment by SylvainCorlay** [comment]
@jdfreder thanks, I actually have to do a similar kludge in the local require-js shim of bqplot.

**Comment by jdfreder** [comment]
:( That's horrible.  Once we move everything to a better, node environment, we wont have to deal with this.
