### ISSUE TITLE
Suggestion: include warnings about stale cached files during the installation process

### ISSUE THREAD

**Issue by rdhyee** [ipython/ipywidgets#340]
Until recently, I had successfully been able to build the development releases using [your instructions](https://github.com/ipython/ipywidgets/blob/6836a4777050316cdfe7ffa378d47b72f511d95a/README.md#development-install):

```
git clone https://github.com/ipython/ipywidgets
cd ipywidgets
pip install -v -e .
```

But then I started to getting complaints in the browser console that `ipywidgets` wasn't properly installed.  After doing more experimentation than I was hoping, I finally realized `pip install -v -e .` was making use of cached results from previous builds.  Once I cleaned out files and directories not directly under git control with

```
git clean -d -f -x
```
I was able to install `ipywidgets`.

Is cleaning out cached files during installations something others have had to do?

**Comment by jdfreder** [comment]
Yeah, I've seen this problem too.  I thought it was a fluke with my setup because I'm doing some weird things with Python ATM.  Thanks for point this out,

I can
- Add print statements to the install process, which, sadly, we only display if the `-v` flag is used  
- Add warnings about this in the README

Neither of which really solve the problem.  I'd like to have an active solution, that clears the cache for the user, but that may be taboo. @takluyver you're good with Python packaging, any words of wisdom?

I'm not even sure I understand the problem fully, because I've had issues with `pip -e` installations and ipywidgets too.  Is it the package dependencies (static content, like the Javascript) which is causing problems?

**Comment by rdhyee** [comment]
It's obvious I don't have a good understanding of the problem -- what I figured out was something the worked for me.  (It occurred to me that caching was the issue because I noticed how much more quickly it took to install `ipywidgets` after I had installed it the first time.)

**Comment by takluyver** [comment]
I'm not sure what pip might be caching. Development installs that require a build step might be a bit dodgy, but scanning through the setup.py, I can't see what might be the problem.

@rdhyee it sounds like you're doing repeated development installs - is there a reason for that? The normal reason to use development installs (`pip -e`) is so you don't need to do it again when the code changes.

**Comment by rdhyee** [comment]
It seems to me that after the first time an installation has been run, the npm-related parts are cached.  (During the first time, the npm part of the installation seems to be the slow part.)

@takluyver I've been rerunning `pip install -v -e .` mostly out of not understanding that I didn't need to do so with every update of the code. On occasion,  I've wanted to switch between using the latest released version on PyPI and the development version, leading me to run  `pip install -v -e .`  more than once.

**Comment by takluyver** [comment]
npm may well be caching downloaded packages, which might explain the speedup the second time you run it, but I don't think that should cause any problems.

If you're happy re-running the command, and you want to switch between different versions, you can just use `pip install .` to do a normal install. `-e` links the package from the source directory - the effect is like symlinking it from `site-packages`, but done with an ugly setuptools mechanism.

**Comment by rdhyee** [comment]
Thanks, @takluyver, for your advice.  Great to be pick up new things from knowledgeable people like you!
