### ISSUE TITLE
Confirmation dialogue in ipywidget button

### ISSUE THREAD

**Issue by aggFTW** [ipython/ipywidgets#345]
Hi, how can we trigger a confirmation dialogue from the user when clicking a button?
Thanks!

**Comment by jdfreder** [comment]
This is not something provided by the widgets out of the box, you'll have to write some Javascript to get this to work.  Because a confirmation dialogue lives at the document level, it probably makes sense to just use a comm and custom messages to accomplish this.  As a result, it will be easiest to implement the whole thing asynchronously.

Something like this:  
- backend "python: `confirm(msg, callback)`"  
- backend->frontend "hey, display a dialogue with `msg`!"  
- frontend "javascript: `confirm(msg);`"  
- frontend->backend "here's the result boolean"  
- backend: "python invoke `callback`"

**Comment by aggFTW** [comment]
Thanks @jdfreder!
