### ISSUE TITLE
provide a wrapper widget for matplotlib plot

### ISSUE THREAD

**Issue by zhuobao** [ipython/ipywidgets#378]
Hi, 
Although there are unofficial solutions (e.g. scikit-spectra) of merging matplotlib plot into widgets, so that together with the existing widgets, they can form a more well aligned interface (comparing to the current case in which plot can only aligned vertically and separately with widgets). I sincerely hope to have an official widget wrapper that convert matplotlib plot figure object into widget, so that buttons and controls and the plot can be easily arranged using vbox, hbox and event passing and updating between controls and plots can be as easy as possible.

**Comment by jdfreder** [comment]
Hi @zhuobao , have you tried the output area widget?  The output area widget doubles as a context manager and should capture all output including matplotlib plots.

**Comment by prinsherbert** [comment]
It works with `%matplotlib inline` but not `%matplotlib notebook`.

Minimal failing example:

    %matplotlib notebook
    
    from matplotlib import pyplot
    from ipywidgets import Output
    from IPython.display import display
    
    out = Output()
    with out:
        pyplot.plot([5,6,4], [4,5,6])
        pyplot.show()
    
    display(out)

**Comment by jasongrout** [comment]
It looks like this is because the `%matplotlib notebook` code makes some strong assumptions about where it will be in a notebook, in particular, its code only works if the output is a direct output of a cell:

https://github.com/matplotlib/matplotlib/blob/6044a571a373d62c2ef78ce977f9ff1ea131146a/lib/matplotlib/backends/web_backend/js/nbagg_mpl.js#L183

This is a problem that will need to be fixed in the matplotlib codebase as a first step to see if we can get it working in the output widget.
