### ISSUE TITLE
Image is repositioned improperly when redrawn using slider

### ISSUE THREAD

**Issue by poldrack** [ipython/ipywidgets#386]
This occurs with the latest ipywidgets and jupyter notebook built from the git repo.  When I move the slider and jupyter redraws the image, it repositions the screen so that half of the image is off the screen towards the bottom, thus obscuring part the image.  I see this behavior on Safari, Chrome, and Firefox on Mac OS X 10.11.3. Here is an example notebook to generate the problem:

https://github.com/poldrack/jdm/blob/master/roulette/roulette.ipynb

Not sure if this belongs here or in the Jupyter issues - let me know if I should move it there.

**Comment by jdfreder** [comment]
I've been in email contact with @poldrack helping him out.  I'd like to echo some of the conversation there in this issue for future visitors.

In the roulette example @poldrack shares, he prints and displays a plot at the same time.  Both of these operations are separate display calls which is what causes the misalignment and some of the flickering.  This is a problem with how the notebook does it's rendering, but it doesn't really have a clean solution (see the clear_output related PRs in ipython/ipython, there's many).

As a workaround, a widget label can be used instead of print.  Here's a slightly modified version of the last cell in @poldrack 's example showing how this can be done: https://gist.github.com/jdfreder/c8b8907c017065fc9758

The underlying function isn't quite fast enough to make the interact response "feel smooth".  As a workaround I suggested to @poldrack to use either `continuous_update=False` or `interact_manual`.  @poldrack found there was a bug preventing `continuous_update=False` from working, the fix is here: https://github.com/ipython/ipywidgets/pull/398

**Comment by jdfreder** [comment]
If anyone encounters this issue in the future and my suggestion above doesn't work, we can re-open the issue...  Actually we may move the conversation to jupyter/notebook
