### ISSUE TITLE
Review of 6.x changes

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#544]
We spent some time today with @jasongrout reviewing the changes in the 6.x branch (PR #538).

 - In `utils.js`
   - `escape.html` should use `textContent` instead of `innerHTML`
   - `typeset` should use `Array.prototype.map` instead of a for loop.

- In lots of places, the double quotes were replaced with single quotes and `'` had to be escaped, which highlighted that we should replace `couldn't` with `could not` in most error messages.

- In `widget_bool.js` why is the `fa` class removed from `<i />`? 

- In `widget_box.js`, missing quotes around class `vbox`.

- In the color picker, `addEventListener` is called twice on the color picker, while in the original widget, it was called once on the picker and once on the text input.

- In `widget-int.js` we are still using the bootstrap class `form-control`. #529 seems to be fixing it.

**Comment by SylvainCorlay** [comment]
cc @afshin

**Comment by afshin** [comment]
@SylvainCorlay @jasongrout,

> escape_html should use textContent instead of innerHTML

Just to be clear, which of these behaviors do we want? (Please see attached screenshot.)

<img width="344" alt="screen shot 2016-04-29 at 12 49 19 pm" src="https://cloud.githubusercontent.com/assets/159529/14915204/facfa50a-0e08-11e6-8c5f-340b09a49ce5.png">

It seems clear that we do not want the first or the last. Of the middle two, one *escapes* the HTML and one strips it. Given that the function is called `escape_html`, I imagine we want the one with all the HTML character entities in it, but please confirm.

> typeset should use `Array.prototype.map` instead of a `for` loop.

Could you explain the rationale for this? `typeset` is called in a lot of places:

1. A `for` loop is faster than `map`.
2. Perhaps even the `for` loop is unnecessary: are there actually cases where `typeset` is returning an array? The reason it currently does is because we were trying to keep a 1:1 fidelity with the `jQuery` version, but if it's actually the case that individual elements are passed in instead of collections, perhaps we can get rid of the loop altogether.

> In lots of places, the double quotes were replaced with single quotes and `'` had to be escaped, which highlighted that we should replace `'couldn\'t'` with `'could not'` in most error messages.

Good call.

> In `widget_bool.js` why is the fa class removed from `<i />`?

Because it is not necessary. An `<i>` tag can be given a `FontAwesome` icon without needing that class. For example, the caret in the `DropDownView` widget has the following style:

```
i.widget-caret {
    font-size: 1em;
    font-style: normal;
    font-family: FontAwesome;
    line-height: 1em;
    position: relative;
}

i.widget-caret:before {
    content: "\f0d7";
}
```

> In widget_box.js, missing quotes around class vbox

Bug! Nice find.

> In the color picker, addEventListener is called twice on the color picker, while in the original widget, it was called once on the picker and once on the text input.

This probably happened when I was trying to rebuild the original PR. Another bug!

> In widget-int.js we are still using the bootstrap class form-control. https://github.com/ipython/ipywidgets/pull/529 seems to be fixing it.

I still see a reference to `'form-control'` in my outstanding PR. But since this is a separate issue, perhaps a separate PR?

**Comment by jasongrout** [comment]
1. `escape_html` should escape, just like you have it. Thanks
2. Good call - it looks like every call now is just asked to typeset a single element. Let's get rid of the for loop and assume `element` is a single element - that will simplify the code a lot. Thanks for catching this.
3. Thanks
4. The `fa` class also sets other things like the font size that correspond to the design of FontAwesome, which I think has ramifications for having pixel-perfect icons, etc (https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L14). @SylvainCorlay, can you comment? It also makes things forward-compatible with css that FontAwesome may need (because they would change the `fa` class to reflect changes in the library, presumably)
5. Thanks.
6. Thanks.
7. Thanks.

Thanks again for your work on this!

**Comment by SylvainCorlay** [comment]
A couple of issues that are master-only:

- The vertical progress bar has the horizontal shape:

<img width="509" alt="screen shot 2016-04-30 at 12 23 07 am" src="https://cloud.githubusercontent.com/assets/2397974/14933859/98bb758a-0e6a-11e6-84b0-575f2034b26c.png">

(It seems to be filling vertically as expected but has the wrong shape). In 5.x it has the same height as the slider.

- The color picker does not have the standard width anymore.
- The dropdown 's width should be the standard width including the description.

<img width="692" alt="screen shot 2016-04-30 at 12 23 25 am" src="https://cloud.githubusercontent.com/assets/2397974/14933853/7c8124a0-0e6a-11e6-9e80-8930b17af04f.png">

**Comment by jasongrout** [comment]
@afshin ^

**Comment by afshin** [comment]
Thanks, @jasongrout and @SylvainCorlay! I'll be looking at these today!

**Comment by afshin** [comment]
With the new bugfixes:
<img width="911" alt="screen shot 2016-05-03 at 7 24 19 pm" src="https://cloud.githubusercontent.com/assets/159529/14993860/c3a1809e-1164-11e6-8705-f2cda3f6da9a.png">

**Comment by SylvainCorlay** [comment]
Does it align well with the vertical slider?

**Comment by afshin** [comment]
@SylvainCorlay there might be some tweaks that would make it better. I'll take a look at the CSS:

<img width="799" alt="screen shot 2016-05-03 at 7 41 00 pm" src="https://cloud.githubusercontent.com/assets/159529/14994308/0c0b3490-1167-11e6-82e3-9160e77662b2.png">

**Comment by afshin** [comment]
FYI: https://github.com/ipython/ipywidgets/pull/557/files

**Comment by afshin** [comment]
FYI, I added the `.fa` class back in for button icons.

<img width="1148" alt="screen shot 2016-05-03 at 9 03 21 pm" src="https://cloud.githubusercontent.com/assets/159529/14996604/ac686b96-1172-11e6-9d6e-bdab1f03acde.png">
