### ISSUE TITLE
All output_area elements are getting rerender on a notebook save

### ISSUE THREAD

**Issue by lbustelo** [ipython/ipywidgets#554]
We noticed this recently and seems to be due to https://github.com/ipython/ipywidgets/blob/3a06dc11311e4d290227d9270729b15c3824b2ca/widgetsnbextension/src/manager.js#L592. This function executes on each notebook `save` and does not seem to filter which `output_area` to redisplay.

It is causing [this](https://github.com/jupyter-incubator/declarativewidgets/issues/339) issue in declarativewidgets.

/cc @SylvainCorlay @parente

**Comment by lbustelo** [comment]
![deletesnapshot](https://cloud.githubusercontent.com/assets/2474841/14993496/9d8e134c-1130-11e6-8770-c166badd9afb.gif)

Notice that the `HelloWorld` text flickers on each save

**Comment by lbustelo** [comment]
I'm trying to figure out what is a good fix here for https://github.com/ipython/ipywidgets/blob/3a06dc11311e4d290227d9270729b15c3824b2ca/widgetsnbextension/src/manager.js#L592 but I'm not clear what this method is supposed to do. 

First... it is running on all the cells... that seems wrong. Second... not sure on what cells should it run.

**Comment by lbustelo** [comment]
@parente Maybe you want to add here the behavior that were seeing with scrolling that may gave to do with this issue and did not involve declarativewidgets.

**Comment by parente** [comment]
I haven't nailed it down, but in a notebook purely using ipywidgets, I'll be working down near the bottom of the notebook, and when the autosave kicks in, I'll suddenly jet to the top. I haven't paid too much attention to the situation when it happens, but I wondered if some ipywidget was suddenly getting focus or something because it's being recreated.

**Comment by parente** [comment]
I did find a simple reproducible example:

1. Create / load a pandas Dataframe with many columns.
2. Display it as HTML in the notebook.
3. Scroll horizontally so that you're looking at the right-most column.
4. Save the notebook.
5. The table is removed and re-added so that it loses the scroll position.

Basically, the code needs to change to only remove/add cells with widgets (or not do that at all). But, yea, which cells are those?

**Comment by minrk** [comment]
It's more specific than that, even - it only needs to do this when the outputs include rendered widget snapshots. I have an idea for how to do it without re-rendering anything.

**Comment by lbustelo** [comment]
Could it be done to also only target the specific Dom fragment within the output area?

**Comment by minrk** [comment]
#591 should fix this, but I'm not 100% confident that it does everything needed. @lbustelo can you test it?

**Comment by lbustelo** [comment]
@minrk I can test it, but I would not be able to tell you if it is the right fix for ipywidgets.
