### ISSUE TITLE
How to distribute widgets?

### ISSUE THREAD

**Issue by gabrielelanaro** [ipython/ipywidgets#563]
Hi, I'm a widget author: https://github.com/gabrielelanaro/chemview and as of  notebook=4.2.0 I'm having problems loading the widgets. (ipywidgets=4.2.0 as well)

The widget files installation happens when the user calls a function enable_notebook as described here:

https://github.com/gabrielelanaro/chemview/blob/master/chemview/install.py

Modules are loaded using requirejs as per here:

https://github.com/gabrielelanaro/chemview/blob/master/chemview/static/chemview_widget.js

I've seen there is a two step installation process followed by projects such as pythreejs, but I can't find a guide on how to make something similar for my project.

Any tips?

So far the program manages to find the right paths using require. However, now I'm getting a timeout error when loading /nbextensions/widgets/widgets/js/widgets.js

```
utils.js:785 Couldn't create a view for model id '06314c6fb47d4835a47214115beace98'  --  Error: Load timeout for modules: /nbextensions/widgets/widgets/js/widget.js
http://requirejs.org/docs/errors.html#timeout
    at makeError (http://localhost:8889/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:165:17)
    at checkLoaded (http://localhost:8889/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:693:23)
    at http://localhost:8889/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:714:25
```

**Comment by SylvainCorlay** [comment]
Hi @gabrielelanaro thanks for your message. The chemview widgets looks *really* cool!

The javascript API has changed quite a bit with ipywidgets 5.0 but from now on it should be much more stable as we have formally created an NPM package for the front-end code (jupyter-js-widgets), which will follow the semver convention for version numbering.

Instead of requiring `/nbextensions/widgets/widgets/js/widgets.js`, you probably want to require `jupyter-js-widgets`, same for any JavaScript of the core widgets.

I have juste created a "template" repository for custom widget authors who want to get started: https://github.com/jupyter/jupyter-widget-example.git

(all of it is in the PR https://github.com/jupyter/jupyter-widget-example/pull/1 at the moment)

If you follow that scheme for you custom widget, you will benefit from the new features such as the embedding of widgets in other websites than the notebook. (See screencast below):

![screencast](https://cloud.githubusercontent.com/assets/2397974/15071400/37ebe660-1359-11e6-812c-559a61bc751f.gif)

This repo is soon going to be changed into a "cookie cutter" template that you can use to generate a new shell for a custom widget project.

**Comment by gabrielelanaro** [comment]
Thanks so much for working on that, I'm very happy that the widgets js api is stabilizing! I'll migrate to the new widget project template.

**Comment by SylvainCorlay** [comment]
@gabrielelanaro I updated the example and made it a cookiecutter template, so that you can generate all the boilerplate automatically.

The project is available here: https://github.com/jupyter/widget-cookiecutter
