### ISSUE TITLE
proper way to update widget stycle (such as font-size) ?

### ISSUE THREAD

**Issue by patrickhoebeke** [ipython/ipywidgets#577]
Hello,
I've noticed that since version 5.0 it is not possible to set style parameters such as 'font-size' with the following syntax
```python
from ipywidgets import widgets
w=widgets.Text("example",font_size=75)
display(w)
```
neither this way:
```python
from ipywidgets import widgets
w=widgets.Text("example")
w.font_size=75
display(w)
```

What is the proper way? 
I've found anything in the doc :-(

**Comment by SylvainCorlay** [comment]
All the *layout-related* style attributes can be accessed through the `layout` widget attribute. Other style-related widget attributes are deprecated.

What you can do is add css class the top-level element if you have custom css in the page.

**Comment by patrickhoebeke** [comment]
Thanks Sylvain you for your answer. Could you add a small example ?

**Comment by SylvainCorlay** [comment]
You can check out and execute the "Flexbox" example : https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Flexbox%20Layout.ipynb

which shows the main possibilities.

**Comment by meowklaski** [comment]
This link is broken - could you point me to another example in which font size is specified?

**Comment by SylvainCorlay** [comment]
Yes, the example notebooks have changed

https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20Styling.ipynb

**Comment by SylvainCorlay** [comment]
Although modifying top-level styling attributes was deprecated in 5.x. Only layout related things are recommended. 

Non-layout related style modification was broken in 5.1, and I intend to make a minor release of 5.x fixing it.

**Comment by djleach-belcan** [comment]
It does not seem possible to modify the font size or color of a Label or Text widget. How should this be accomplished?

**Comment by meyermj** [comment]
Is there any hack available to set the font size and color of a Text widget? Widgets are great for usability, but the small default font makes it hard for some users to see.

**Comment by sjdv1982** [comment]
@meyermj, @patrickhoebeke : I had the same problem. 
After studying what CSS is and how it works, I managed a hack:

```python
import ipywidgets
w = ipywidgets.Text("test", description="Title")
w.add_class("mytext")
w
```

```
%%html
<style>
.mytext > .widget-label {
    font-style: italic;
    color: blue;
    font-size: 30px;
}
.mytext > input[type="text"] {
    font-size: 20px;
    color: red;
}
</style>
```
Note that %%html is simply a wrapper around IPython.display.display_html. So it would be possible to create some kind of Pythonic front-end that generates and displays the CSS. At the very least, one could use something less awkward than pure CSS (it appears that there are dialects with improved syntax, like SASS, which are pre-processed/compiled into CSS).

But, in addition, one could inform a smart front-end about the internal DOM structure of the ipywidget.To my taste, this is a more flexible way to allow styling than the current method of exposing arbitrary attributes to the model-view-comm framework. But I am not really qualified to judge, since I know nothing about front-end development.

**Comment by jasongrout** [comment]
The DOM structure of the frontend widget is explicitly an implementation detail, so it is not exposed to the user as an API. However:

1. we do have a flexible framework for adding such styles to the various style attributes on widgets (for example, we recently added a style attribute to buttons that lets you set the ToggleButtons font weight with something `ToggleButtons(options=['a','b','c'], style={'font_weight': 'bold'})`

2. For systematic changes across all widgets, a theme setting is probably better. The Jupyter notebook isn't designed for theming, but JupyterLab is, and there it is much easier to change the system-wide font size, which would also affect ipywidgets.

**Comment by jasongrout** [comment]
That said, the hack above works, but it is fragile and relies on implementation details that may change.

**Comment by sjdv1982** [comment]
> we do have a flexible framework for adding such styles to the various style attributes on widgets  (for example, we recently added a style attribute to buttons that lets you set the ToggleButtons font weight )

Hmm... Is this flexible framework documented somewhere? How does it work? 
I can't speak for others, but as a Python developer, I have a certain set of expectations:
- We're all consenting adults, we don't hide properties from each other.
- Everything must be accessible via Python. I won't learn TypeScript or Backbone just to expose a simple styling property. 
- Interactiveness. I won't re-build the ipywidgets module just to expose a simple styling property.
- I will write pure HTML/CSS/JS if I have to, but I much prefer a Pythonic API.

> That said, the hack above works, but it is fragile and relies on implementation details that may change.

It is fragile, because the implementation details (the widgets' internal DOM structures and class names) are hard-coded into the CSS. A CSS generator that would be aware of these details would not be fragile.

**Comment by jasongrout** [comment]
Here is an example of a PR that adds two style attributes to toggle buttons: https://github.com/jupyter-widgets/ipywidgets/pull/1834

Unfortunately, we don't have a good tutorial about adding style attributes yet. We're happy to answer questions, though, and perhaps that would be a good start of a tutorial.

We have a very explicit (and at this point, fairly limited but expanding) styling api so that we can maintain backwards compatibility even as we change the implementation details of the DOM structure. If you'd like to work on abstracting things out a different way, please elaborate so we can start a design discussion.

**Comment by jasongrout** [comment]
Here is the documentation of the existing styling attribute system: http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html

**Comment by jasongrout** [comment]
One of the goals of the existing `.style` attributes is that you can style things from python, without having to write css or javascript. The current system does require that specific styling attributes have to be explicitly exposed to python, which is #1834 is doing.

**Comment by sjdv1982** [comment]
@jasongrout  @SylvainCorlay 
I feel it's not very Pythonic to hide away styling properties if they are not explicitly exposed via TypeScript / Backbone. It's more of a Java mindset.

Also:
In the future, I could help Granny remotely to fill in her taxes using a Jupyter collaborative tax form notebook. In that case, Granny may prefer a font size bigger than I do. 

Are you sure that model-view-comm state sync is the best way to specify styling attributes?

**Comment by SylvainCorlay** [comment]
It is not about encapsulation. It is about what is part of the API, and what is implementation detail. If everything is considered API, any change can be considered a breaking change.

We let ourselves the privilege to change the DOM representation of widgets (which would break most direct uses of CSS), which is why we only expose a whitelist of attributes to the backend.

**Comment by jasongrout** [comment]
> If you'd like to work on abstracting things out a different way, please elaborate so we can start a design discussion.

For future readers - it seems like this discussion and design proposal are split between this thread and the messages starting at https://github.com/jupyter-widgets/ipywidgets/issues/1840#issuecomment-353729715.

@sjdv1982 - to make it easier for others to follow the discussion and to better archive it, I suggest we open a new issue to have a discussion about a concrete proposal. This issue is an old closed issue, and #1840 is a much more scoped issue than what you are proposing.

**Comment by sruthiiyer** [comment]
> It is not about encapsulation. It is about what is part of the API, and what is implementation detail. If everything is considered API, any change can be considered a breaking change.
> 
> We let ourselves the privilege to change the DOM representation of widgets (which would break most direct uses of CSS), which is why we only expose a whitelist of attributes to the backend.

HEY, can tell me how to add the HTML style tag for code tag in ipywidgets

**Comment by Himscipy** [comment]
Hi 👋 All ,
Is there an answer how to increase the font size (ie. not using CSS)?   I couldn't find much detail in the documentation.
Thank you.

**Comment by sruthiiyer** [comment]
> Hi 👋 All ,
> Is there an answer how to increase the font size (ie. not using CSS)? I couldn't find much detail in the documentation.
> Thank you.

Yes we can, You can use inline style tag for increasing the font size

```
out = "<html><head><style>.code-style {font-size: 14px;line-height: 24px;color: black;} </style></head><code class=" +'"code-style"> hello" + '</code></html>'
out = widgets.HTML(value= out)
```

**Comment by Himscipy** [comment]
@sruthiiyer Thank you for your inputs.

> > Hi 👋 All ,
> > Is there an answer how to increase the font size (ie. not using CSS)? I couldn't find much detail in the documentation.
> > Thank you.
> 
> Yes we can, You can use inline style tag for increasing the font size in html
> 
> ```
> out = "<html><head><style>.code-style {font-size: 14px;line-height: 24px;color: black;} </style></head><code class=" +'"code-style"> hello" + '</code></html>'
> out = widgets.HTML(value= out)
> ```

**Comment by gsteele13** [comment]
Just to follow up on this discussion: 

If I understand correctly, it seems that it is not possible to change font size for a single specific Text() widget? 

I can for example of course use the HTML text widget and there modify the HTML widget text properties, eg

```
html = "<h1 style='font-size:100px'> Test font  Test again </h1>"
widgets.HTML(value=html)
```

<img width="1102" alt="Screenshot 2021-01-06 at 17 40 00" src="https://user-images.githubusercontent.com/16204006/103795428-3f029a00-5046-11eb-97c3-37f57391f123.png">

But there is no way to change the size of the text of a `widgets.Text()` widget, or any other widget? 

By the way, I get some weird stuff if I do this:

<img width="1089" alt="Screenshot 2021-01-06 at 17 39 44" src="https://user-images.githubusercontent.com/16204006/103795444-445fe480-5046-11eb-91ea-889a9f410083.png">

It seems the estimated height of the HTML is not correctly calculated with non-header elements when changing font size...?
