### ISSUE TITLE
Let's improve the install instructions...

### ISSUE THREAD

**Issue by fperez** [ipython/ipywidgets#586]
After my struggle with #582, I think we should clarify the instructions for this package a bit. I've already wasted multiple hours, multiple times, trying to get widgets to work.  I think a small amount of work on our docs here will help folks a lot, and lower the barrier for people who want to contribute in the future (which most likely means running from master).

The main top-level README doesn't say anything about running the npm command (see #582 for context): should it? Right now, the installation instructions for this repo are confusing:

1. A main README that doesn't mention anything about npm.
2. The README links to an install doc that supposedly has more details, but in reality only repeats what the README says.
3. The README in js-widgets that indicates npm needs to be run in the main repo.

Additionally, I finally figured out that my problem was due to widgetsnbextension having been updated, and I was running from source via `pip install -e`. So what ended up working was a pip reinstall (uninstall/install) that forced a pull of the new, correct version of widgetsnbextension.

I think we should provide:

1.pip/conda only install directions.
2. "Run from source" directions if there's anything else to do beyond adding `-e .` to `pip install` (e.g. `npm` calls).
3. An explicit note about anything users need to know (or not) regarding the js-widgets subpackage and `widgetsnbextension`.

A little clarification of these issues will help a lot with anyone trying to use this project.

**Comment by jdfreder** [comment]
I'm going to start tackling this in https://github.com/ipython/ipywidgets/pull/585

**Comment by psychemedia** [comment]
I'm running a recent version of Jupyter with a remore `ipython` kernel and wondered whether I'd be able to use `ipythonwidgets` with that remote kernel.

If it is possible to do that, the install requirements seem to pull down huge chunks of the Jupyter framework, which seems like overkill? (The reason I want to run the the IPython kernel remotely is because I want to minimise overhead on that device.)

**Comment by SylvainCorlay** [comment]
@psychemedia you *can* actually only install the required parts on the kernel-side without requiring the notebook server.

- on the notebook server side (you main PC), only install `widgetsnbextension` and then `jupyter nbextension install --py widgetsnbextension`.
- on the kernel side, what you can do is install `ipywidgets` with `--no-deps`and then install the following requirements if it is not already there:
```
    'ipython>=4.0.0',
    'ipykernel>=4.2.2',
    'traitlets>=4.2.0',
```
and things should work.

In fact, the dependency of `ipywidgets` (the kernel code) to `widgetsnbextension` (the javascript to be served by the notebook server) is something that we added so that users who install it on a single machine would get the whole enchilada without having to install multiple things.

We yet have to figure out how to reconcile the two approaches:
 - have a decoupled installation for users like you who want to have a lightweight python install on the kernel side (for devices such as the mindstorm you work on)
 - have a simple "one click" install for users working on a full-fledged anaconda distribution.

**Comment by psychemedia** [comment]
@SylvainCorlay Great - thanks for that, I'd missed the `--no-deps`.

One other thing I've noticed is that I'm getting a `The installed widget Javascript is the wrong version.` warning in my notebooks. Can this arise because of a mismatch between the notebook on host and `ipywidgets` in the remote kernel, or do I have another issue?

**Comment by ryanpepper** [comment]
I'm having trouble with the Anaconda installation instructions as they stand - when I create a new conda environment as follows, I get the "Installed widget Javascript is the wrong version." This is with Anaconda 4.0.8 installed clean.

> conda create -n test python=3.5
> conda install -c conda-forge ipywidgets

**Comment by fperez** [comment]
I'm seeing also the `JS wrong version` message intermittently.  I was busy using this with other work so I didn't have time to chase it down, but it was very confusing, as it was happening on some notebooks but not others *simultaneously* (i.e., running off the same server).  Very odd.

**Comment by SylvainCorlay** [comment]
Same kernel?

**Comment by fperez** [comment]
Same type of kernel, yes, though different instantiations thereof (meaning, separate notebooks, but all on the same IPython/Py3 kernel, which is my default). Unfortunately this was last week in the middle of a marathon workshop and I can't reproduce it now.  If I can get the problem back I'll post more details.  But I was seeing that red JS warning for sure :)

**Comment by minrk** [comment]
I've seen it intermittently as well, only just recently I think. I don't know if it could be a cache issue or a race somewhere. I cleared out everything and installed from conda-forge, and it seems to have gone away, so it might be something in master.

**Comment by SylvainCorlay** [comment]
comms were broken in ipykernel master for a bit because of https://github.com/ipython/ipykernel/issues/137

**Comment by SylvainCorlay** [comment]
I think that we have quite improved the situation here. Hopefully, `conf.d` approach should intrinsically simplify things, but in terms of documenting the current situation, we are in a better state.

**Comment by fperez** [comment]
Many thanks everyone for taking this seriously, it's really important and I feel like we'd let the code get a bit ahead of ourselves, so I'm very happy to see progress here (even though I know that it takes time).

**Comment by SylvainCorlay** [comment]
As per discussion earlier with Brian, I find it a bit worrying that (even very minor) PRs involving a UI component require so much validation.

Before we adopt a very formal process on the jupyter.org website

**Comment by SylvainCorlay** [comment]
As per discussion earlier with Brian, I find it a bit worrying that (even very minor) PRs involving a UI component triggers so much discussion, and requires so many people to get involved before things get merged.

Before we adopt a very formal process for the jupyter.org website, we should get to a more acceptable state. There are tons of easy wins and simple issues that we can fix, and we could fix the most obvious problems by iterating quickly and through drive-by contributions...

**Comment by fperez** [comment]
@SylvainCorlay, did you mean to reopen this or was this comment meant to be in the website repo?

Otherwise I'm actually in agreement with you (hence my language on your [#109 PR](https://github.com/jupyter/jupyter.github.io/pull/109)) :)

**Comment by SylvainCorlay** [comment]
That comment was meant for the other PR... Thanks!
