### ISSUE TITLE
Dependencies are not necessarily checked

### ISSUE THREAD

**Issue by vbraun** [ipython/ipywidgets#597]
If setuptools is not present the dependency information is discarded; I take it this is to support distutils:
~~~~
if 'setuptools' in sys.modules:
    setup_args.update(setuptools_args)
~~~~
Thats nice that I can install it without setuptools, of course it won't work because of missing dependencies. 

Really, I think you should go with the times and require setuptools. The alternative is using distutils require= or manual checking.

See also: http://trac.sagemath.org/ticket/20625

**Comment by vbraun** [comment]
Even with setuptools installed I can `python setup.py install` ipywidgets despite widgetsnbextension not being present.

**Comment by minrk** [comment]
`python setup.py install` doesn't invoke setuptools, because its behavior is horribly broken when setuptools is used. So if we did require setuptools, we would explicitly disable `setup.py install` if called without pip. For basic local installation, `pip install .` should be used (this is true of ~all Python packages, especially if they use setuptools).

**Comment by vbraun** [comment]
I'll be happy to use pip as soon as it either doesn't require openssl or the latter switches to a free license...
