### ISSUE TITLE
update options on Selection Widget

### ISSUE THREAD

**Issue by marqh** [ipython/ipywidgets#621]
I would like to update the options on a selection widget.  this 'just worked' in ipywidgets v4 but v5 has more validation

I have written what feels like a clumsy work around pattern to enable me to get the functionality I want.  
I would greatly appreciate advice on what I'm trying to achieve and how to do it better

```
import ipywidgets
import IPython
import numpy as np

rands = ipywidgets.Dropdown(
    description = 'Random numbers:',
    options = {},
)

make_rands = ipywidgets.Button(description='randomise')

def randoms(sender):
    rands.options['None'] = None
    rands.value = None
    vals = np.random.random(4)
    options = [(str(r), r) for r in vals]
    rands.options = dict([('None', None)] + options)
    rands.value = options[0][1]
    rands.options = dict(options)


make_rands.on_click(randoms)

IPython.display.display(rands, make_rands)
```

**Comment by marqh** [comment]
note, using ipywidgets 5.1.3

**Comment by marqh** [comment]
my initial simple attempt fails with a 
```
TraitError: Invalid selection
```

```
import ipywidgets
import IPython
import numpy as np


rands = ipywidgets.Dropdown(
    description = 'Random numbers:',
    options = {},
)

make_rands = ipywidgets.Button(description='randomise')

def randoms(sender):
    vals = np.random.random(4)
    options = [(str(r), r) for r in vals]
    rands.options = dict(options)


make_rands.on_click(randoms)

IPython.display.display(rands, make_rands)
```

**Comment by SylvainCorlay** [comment]
Indeed, we should probably allow setting a new set of options that does not contain the current value.

In the mean time, you can do

```
with sel.hold_trait_notifications():
    sel.value = 3
    self.options = {'a':1, 'b':2}
```

**Comment by elainethale** [comment]
I am hitting this problem as well, which appears to be triggered by circular trait-checking. In particular, setting.options eventually calls _Selection._value_in_options() at (line 88 of widget_selection.py)[https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_selection.py#L88]. This in turn tries to set .value, which results in checking the new value (pulled from _Selection._options_values) against .options, which hasn't been set to the new value yet!  The problem could be fixed by validating .value against ._options_values instead of .options, or something similar ... 

In the meantime, thanks for the workaround @SylvainCorlay!
