### ISSUE TITLE
button for playing slider?

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#625]
hi,

I want to create a button (B) that link to IntSlider object (A). First click B will increase the value of `A` every 1 second. Click B again will interrupt the process.

Any idea how to do it? I've searching google, looking at ipywidgets example but still have no clue now.

Please note that we already created a button player in JS frontend but I want to try `ipywidgets`'s Button too.

![](https://raw.githubusercontent.com/arose/nglview/master/nglview.png)

PS: I intended to send to suggested Jupyter maillist but seems making it scattering.

**Comment by SylvainCorlay** [comment]
Rather than making a loop on the python side, I would create a new widget that uses the browsers' event loop on the js side with setTimeout.

So widget whose view is a sort of play button, and the model iterates over integers between 0 and the set maximum with an interval also set with a trait attribute....

I think that ipywidgets would be the right place for such a widget.

**Comment by hainm** [comment]
> Rather than making a loop on the python side, I would create a new widget that uses the browsers' event loop on the js side with setTimeout.

thanks for you feedback.
We actually have that in js side: https://github.com/arose/nglview/blob/master/nglview/js/widget_ngl.js#L209-L221

but it would be great if having that in `ipywidgets` (like you said) too. Cheers.

**Comment by SylvainCorlay** [comment]
This was added in #633 !
