### ISSUE TITLE
Can't jslink Play and IntSlider

### ISSUE THREAD

**Issue by gapar2** [ipython/ipywidgets#698]
I want to combine the Play widget with the IntSlider so that the user can either play from 1 to 100, or manually select a certain value.

For this given snippet, the IntSlider behavior is as expected (numbers are printed based on the position of the slider). When I click on the Play button, the slider does go up (e.g., from 1 to 2 to 3, every 2000 ms), but no numbers are printed.

```
def on_value_change(change):
    print(change['new'])

slider = widgets.IntSlider(min=1, max=100, step=1, continuous_update=False)
play = widgets.Play(interval=2000)
widgets.jslink((play, 'value'), (slider, 'value'))
slider.observe(on_value_change, names='value')
widgets.VBox([play, slider])
```

**Comment by gapar2** [comment]
@SylvainCorlay  I read your commit [633](https://github.com/ipython/ipywidgets/pull/633/files) but my knowledge of Jupyter MVC is too basic to be able to dive deep into this. It could very well be the case that I'm misunderstanding how jslink and observe are supposed to be used.

**Comment by SylvainCorlay** [comment]
@gapar2, you are actually triggering a very subtle corner case of the behavior of interactive widgets:

If you do
```python
from ipywidgets import *
def on_change(change):
    print(change)
s = IntSlider()
s.observe(on_change, names='value')
```

and then, in two different cells, you display a different view of `s`:
```python
s
```
 and 
```python
s
```

Moving the first slider will print under the first cell, and moving the second slider will print under the second cell. The reason is that we keep track of the view that originally triggered the event, and we print stdout messages in the cell that holds the view.

In the case of the play widget, the *model* is the one that triggers the original message and there is no view to associate it with.

In your code, if you had done

```python
l = []
def on_value_change(change):
    l.append(change['new'])

slider = widgets.IntSlider(min=1, max=100, step=1, continuous_update=False)
play = widgets.Play(min=1, interval=2000)
widgets.jslink((play, 'value'), (slider, 'value'))
slider.observe(on_value_change, names='value')
widgets.VBox([play, slider])
````

you would see that the list `l` changes as expected. The only problem is that there is nowhere to route the `print` messages.

At the moment we don't really have a natural solution to this. My take on this was that we should have a global output area to the notebook for messages that are not uniquely associated with a single cell.

In the meantime, I recommend you print textual content in a `Text` or a `Label` widget.

**Comment by gapar2** [comment]
Thank you for the update. The Text/Label trick works, thanks!
