### ISSUE TITLE
Resolution order for models with children models

### ISSUE THREAD

**Issue by abelnation** [ipython/ipywidgets#737]
On both the python and javascript side, I'm trying to determine the following:

Given a model that contains references to other models (either a single instance, or a collection, e.g. a parent/child relationship), is there any guarantee about the order or construction for the models? 

In other words, can a parent model assume that all of it's children models are fully instantiated when it is being constructed?  If not, is there some mechanism or hook to use when all models have been fully constructed?  

Thanks!

**Comment by jasongrout** [comment]
Are you constructing the widgets in python? Then yes, the children models should be instantiated before the parent is. What is your use case?

**Comment by abelnation** [comment]
The objects would be constructed via the ipy interface, so the order of steps would look like:

```
1. ipy~ parent = MyParent()
2. ipy~ child = MyChild()
3. ipy~ parent.add(child)
```

I think, when executed one by one, these lines are fairly straightforward, as they explicitly create the models in the right order, but it becomes more complicated when you, for example, reload your browser page.  In that case, the models need to be retrieved from the server and re-instantiated on the client.  In that case, it is unclear whether my ipywidget js models will be instantiated in the right order or not.  

To clarify: at some point, `initialize` will be called for my `parent` js BB model.  When the `parent` js model `initialize` method is called, will calling `.get('children')` return the list of fully instantiated children models (and therefore, a list containing the js model for `child`)?

**Comment by jasongrout** [comment]
I'm a bit rusty on this since things have changed a lot recently (@sylvaincorlay is more current on the code), but:

1. I'm pretty sure it will work fine - that's exactly the sort of thing that pythreejs does a *lot*, and I don't remember problems.
2. the lines are not executed one by one again.  IIRC, either the state is stored in localStorage and the relevant bits are pulled out based on a server request about active comm objects, or a new state is loaded from server (I think the former is what happens).

Were you seeing a problem, or are you just making sure the system handles your use case, or something else?

**Comment by abelnation** [comment]
Not seeing a problem, just trying to make sure I understand the framework before investing too much time going down a specific path.  Thanks!

**Comment by SylvainCorlay** [comment]
@abelnation I am doing some issue triage. Closing this one since there was not any problem.
