### ISSUE TITLE
Select box width not extending properly

### ISSUE THREAD

**Issue by alexjlam** [ipython/ipywidgets#773]
I'm trying to use the Select widget and I have some items in it with names that are too long to display for the default size of the Select box width.

Here is what I'm trying to do

```
test = widgets.Select(options=['really long item thats too big for the default selection box width'], description="testwidget")
test.layout.width = '400px'
display(test)

```

Except that the test.layout.width part doesn't extend the widget to 400px. It seems to max out at the default length. I remember I had this same code working properly with some 4.x version of ipywidgets but now I want to use my current 5.2 version.

By the way, the test.layout.height does work properly when I set it to '400px'

**Comment by gnestor** [comment]
@SylvainCorlay I can verify that adjusting the layout's `width` or `height` properties have no effect on the `Select` widget's width/height. I tested using:

```py
test_layout = Layout(width='100%')
Select(options=['really long item thats too big for the default selection box width'], layout=test_layout)
```

Any thoughts?

**Comment by lrq3000** [comment]
I think the same issue is happening here:

https://github.com/tqdm/tqdm/pull/292

**Comment by gnestor** [comment]
I can verify that this issue is resolved on master.

![image](https://cloud.githubusercontent.com/assets/512354/19615202/d7f148e0-97b0-11e6-93c3-cbffee990231.png)

You can wait and upgrade to the new release when it's available or follow the [developer install](https://github.com/ipython/ipywidgets/blob/master/docs/source/dev_install.md) instructions to install master to your local environment.

**Comment by jasongrout** [comment]
Confirmed that it works in master.
