### ISSUE TITLE
Replacing a Dict traitlet doesn't always sync to frontend

### ISSUE THREAD

**Issue by justinmc** [ipython/ipywidgets#786]
I realize that modifying a property of a dictionary won't cause the dictionary to sync (probably rightfully so), but how about something like this?

    my_dict = traitlets.Dict({ 'thing': {} }).tag(sync=True)

    ...

    new_dict = dict(my_dict)
    new_dict['thing']['prop'] = 'whatever'
    # Notice that at this point, self.my_dict == new_dict is True,
    # since they both refer to the same `thing` object

    self.my_dict = new_dict

The above will not cause `my_dict` to be synced to the frontend.  It seems like there might be a value comparison happening somewhere to prevent unnecessary syncing, but it causes unexpected behavior in this case.

**Comment by minrk** [comment]
There is indeed a value comparison preventing the sync. While `dict(my_dict)` works to create a copy if my_dict is shallow, it won't if it's nested, as you surmised. You would need `copy.deepcopy` to make a deep copy of the dict to ensure that you aren't updating the dict in-place.

@SylvainCorlay and @rmorshea are working on eventful dict traits, so that changing an item in a watched dict will trigger a change event.

**Comment by justinmc** [comment]
To be specific, `new_dict = dict(my_dict)` does create a new dictionary, so then `id(new_dict) == id(my_dict)` is False (but the nested `thing` object is shared, like you said).

I think it makes sense for me to just solve my specific problem using a deep copy in the meantime though like you suggested.  It sounds like the work on eventful dict traits is what we really want here 👍 .
