### ISSUE TITLE
Include a new interact API that behaves like Sage's equivalent

### ISSUE THREAD

**Issue by gnestor** [ipython/ipywidgets#813]

**Comment by gnestor** [comment]
@SylvainCorlay Has this already been implemented?

**Comment by SylvainCorlay** [comment]
This has been tackled by @jdemeyer and I think that it is almost code complete in master.

**Comment by jdemeyer** [comment]
> This has been tackled by @jdemeyer and I think that it is almost code complete in master.

There is code at https://trac.sagemath.org/ticket/21267 which is an interact API using `ipywidgets` that behaves (almost) exactly like the old SageNB `@interact` functionality. However, this is not part of `ipywidgets`. It's not clear whether it should be part of `ipywidgets` or not. Maybe some things make sense for `ipywidgets`, others maybe not.

Roughly speaking, there are 4 kinds of things that https://trac.sagemath.org/ticket/21267 implements (roughly in decreasing order of relevance for `ipywidgets`):

1. Several new widgets created by changing or combining existing widgets from `ipywidgets` (there is zero new Javascript). For example, there is an `EvalText` widget which is like `Text` but the value passed to the interactive function is `eval(textbox_string)` instead of `textbox_string`. There is also a `Grid` widget which is an `n` by `m` grid of textboxes whose value is a list of lists of the individual values.

2. New abbreviations for `@interact`, for example a 2-tuple `(default, abbrev)` where `abbrev` is a valid interact abbreviation which is not a single value. Also, an iterator becomes a `SelectionSlider` instead of a `Dropdown`. So `@interact(x=[1,2,3])` given a `Dropdown` while `@interact(x=iter([1,2,3]))` gives a `SelectionSlider`.

3. Support for SageNB widgets constructors. For example, the SageNB class `slider` gets mapped to `SelectionSlider`/`IntSlider`/`FloatSlider` depending on the arguments.

4. Support for Sage-specific data types. For example, symbolic expressions like `log(2)` in abbreviations are evaluated numerically to reals like `0.6931471805599453`.

I will leave it to upstream authors of `ipywidgets` to decide which things changes make sense for `ipywidgets`.

What is still missing from `ipywidgets` to have full support for SageNB interact functionality (roughly in decreasing order of importance):

1. #763: on_click() event for `ToggleButtons`
2. #817: LaTeX or HTML code as widget label
3. #760: `SelectionRangeSlider`
4. A slider which works with arbitrary numerical types instead of only `int` and `float`. However, it is not clear how to deal with this on the Javascript side. Related to #721.

**Comment by gnestor** [comment]
@jdemeyer Ok, thanks for clarifying! I can start working on the 4 issues above. Do we have a timeline for these features?

**Comment by jdemeyer** [comment]
I don't know what you mean with timeline. I wouldn't be able to implement any of the 4 extra needed features myself, since I know too little of Javascript.

**Comment by gnestor** [comment]
What I mean is do you need these implemented within a certain timeframe? I just want to know how to prioritize them against all of the other issues.

**Comment by jdemeyer** [comment]
Actually, I need them to be implemented by August 2016 because of https://github.com/OpenDreamKit/OpenDreamKit/issues/94

Since that deadline has passed anyway, I guess the urgency is gone. The next deadline is the formal review meeting for OpenDreamKit. A date has not been decided, but it will likely be May 2017.

Just curious, I don't know you: why do you care so much about this?

**Comment by gnestor** [comment]
I'm Grant 👋 I've been contributing to Jupyter for a while but recently started contracting for the project. I'm primarily maintaining the notebook and ipywidgets repos. Regarding this issue, I saw that this was on the roadmap for v5 so I wanted to make sure that it was implemented before moving on to other things.

**Comment by jdemeyer** [comment]
I'm Jeroen, working mainly on SageMath for the European [OpenDreamKit](http://opendreamkit.org) grant in [Gent](https://www.google.be/maps/place/Gent). Making the SageMath interacts work in ipywidgets is one of the tasks of this project. Like I said before, this is essentially done, apart from some issues like the 4 I mentioned. It makes little sense to put it on the roadmap for v5 because a lot of functionality that I need will only be available in ipywidgets v6 (if I'm not mistaken).

Of those 4 issues, I consider #763 the most serious because it comes up often in actual use cases. It would be great if this could be done for ipywidgets v6.

The second, #817, is just a display issue so it's less important. The third, #760, has not come up in practice, but I would need it for a range-slider with rational numbers (as work-around for the fourth issue, #721, I use a `SelectionSlider` to handle the cases where `IntSlider` and `FloatSlider` are not sufficient). The fourth issue can be worked around, so I put it as the least important.
